### ISSUE TITLE
Disable obfuscation on debug builds

### ISSUE THREAD

**Issue by somerandomdev49** [khasm-lang/khasmc#2]
Currently the output has unnecessary (imo) obfuscation added to the names. I think it would be great if there was a flag that disables the obfuscation and function/variable names are left unchanged in the output lua code.

**Comment by jake-87** [comment]
Thank you for your concern. Currently, yes, builds are entirely obfuscated beyond what is really reasonable. However, there are two reasons i won’t be doing this:
- I’m going to rewrite the backend pretty soon anyways 
- and I don’t have command line option support yet and probably won’t for a little while :p

Thank you anyway though! ( and congrats on the first issue that wasn’t just me testing and then deleting :D)
